import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../style/header.css";
import Button from "../components/Button";
import Footer from "../components/Footer/Footer";
import Link from "next/link"; // Importação do componente Link do Next.js para a criação de links entre páginas internas do site (mais rápido que o <a> do HTML)
import Image from "next/image"; // tem mais vantagens que a tag <img> do HTML como carregamento de imagens de forma otimizada, porém é necessário colocar o tamanho da imagem no componente

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <header className="flex">
          <Link href="/"><img src="/salesforce-logo.svg" alt="Logo Salesforce" /></Link>
          <nav>
            <ul className="flex">
              <li><Link href="./products">Produtos</Link></li>
              <li><a href="#">Indústrias</a></li>
              <li><a href="#">Aprendizado</a></li>
              <li><a href="#">Suporte</a></li>
              <li><a href="#">Empresa</a></li>
            </ul>

            <div className="header-contact">
              <a href="https://www.salesforce.com/br/form/contact/contactme/?d=cta-header-9">Entre em contato</a>
              <p>0800 891 1887</p>
            </div>

            <img className="language-selector-globe" tabIndex={0} src="/earth-icon.svg"
              alt="icone do globo terreste em linhas pretas" />

            <div className="login">
              <Link href="/login"><img src="/login-02.webp" alt="Logo de login"/></Link>
              <Link href="/login">Login</Link>
            </div>
            <Button link="./free-trial" text="Teste Grátis" />
          </nav>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
