import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../style/header.css";
import Button from "../components/Button";
import "../style/footer.css";
import Footer from "../components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <header className="flex">
          <a href="/"><img src="/salesforce-logo.svg" alt="Logo Salesforce" /></a>
          <nav>
            <ul className="flex">
              <li><a href="./products">Produtos</a></li>
              <li><a href="#">Indústrias</a></li>
              <li><a href="#">Aprendizado</a></li>
              <li><a href="#">Suporte</a></li>
              <li><a href="#">Empresa</a></li>
            </ul>

            <div className="header-contact">
              <a href="https://www.salesforce.com/br/form/contact/contactme/?d=cta-header-9">Entre em contato</a>
              <p>0800 891 1887</p>
            </div>

            <img className="language-selector-globe" tabIndex={0} src="/earth-icon.svg"
              alt="icone do globo terreste em linhas pretas" />

            <div className="login">
              <a href="login.html"><img src="/login-02.webp" alt="Logo de login" /></a>
              <a href="login.html">Login</a>
            </div>
            <Button link="./free-trial" text="Teste Grátis" />
          </nav>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
